
export const TEACHER_LIST = [
  'JULAIHEI @ JULAIHI BIN MAHDI',
  'BEREMAS ANAK INGGIT',
  'HASIAH BINTI SALLEH',
  'VOON CHUN WEI',
  'ANDREA BINTI MOHAMAD SA’AID',
  'SHARLINA BINTI MOHAMAD SHAMSUDDIN',
  'FREDERICK BRYAN YONG',
  'SYLVIA LEE MEI BAY',
  'MUHAMAD ASRI BIN ROSLI',
  'YII CHIN SIEW',
  'USIN ANAK SENTAN',
  'NURSHAFIQAH BINTI MOHD FARIQ ARIFFIN',
  'ESTEE-LAURA ANAK ANTHONY'
];

export const CLASS_LIST = [
  'TAHUN 1',
  'TAHUN 2',
  'TAHUN 3',
  'TAHUN 4',
  'TAHUN 5',
  'TAHUN 6'
];

export const SUBJECT_LIST = [
  'BAHASA MELAYU',
  'ENGLISH',
  'MATHEMATICS',
  'SCIENCE',
  'PENDIDIKAN JASMANI',
  'PENDIDIKAN KESIHATAN',
  'REKA BENTUK TEKNOLOGI',
  'PENDIDIKAN AGAMA ISLAM',
  'PENDIDIKAN MORAL',
  'TASMIK',
  'PENDIDIKAN SENI VISUAL',
  'PENDIDIKAN MUZIK',
  'SEJARAH',
  'BAHASA IBAN',
  'PEMULIHAN - BAHASA MELAYU',
  'PEMULIHAN - MATHEMATICS'
];

export const RELIEF_REASONS = [
  'CUTI REHAT KHAS',
  'CUTI SAKIT',
  'TAKLIMAT/BENGKEL/KURSUS',
  'GURU PENGIRING'
];